import openai

def is_ai_text(input_text, comparison_text, api_key):
    # Set up OpenAI API credentials
    openai.api_key = api_key

    # Generate text with the GPT-3 model
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=comparison_text,
        max_tokens=50,
        n=1,
        stop=None,
        temperature=0.5
    )
    generated_text = response.choices[0].text.strip()

    # Calculate similarity using Jaccard index
    intersection = set(input_text.lower().split()) & set(generated_text.lower().split())
    union = set(input_text.lower().split()) | set(generated_text.lower().split())
    jaccard_index = len(intersection) / len(union)

    # Define a threshold for similarity
    similarity_threshold = 0.5

    # Determine if the text is likely AI-generated
    if jaccard_index >= similarity_threshold:
        return True
    else:
        return False

# Provide your API key and input text for comparison
api_key = "your_openai_api_key"
input_text = "This is a text written by a human."

# Specify the comparison text generated by AI (e.g., from GPT-3)
comparison_text = "The following is a text generated by GPT-3:"

is_ai = is_ai_text(input_text, comparison_text, api_key)

if is_ai:
    print("The input text is likely AI-generated.")
else:
    print("The input text is likely written by a human.")
